# Generated by Django 4.0.3 on 2022-04-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpvapp', '0003_recette'),
    ]

    operations = [
        migrations.AddField(
            model_name='depence',
            name='par',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AddField(
            model_name='recette',
            name='par',
            field=models.CharField(default=0, max_length=500),
        ),
    ]
